
#debug模式，true输出控制台日志，false只输出文件日志
debug: true

#名称
server_name: "cgm"

#server 地址
server_url: "0.0.0.0:7777"

#log 地址
log_path: "requests.log"

#mysql地址
mysql_url: "mysql://root:31415926@Pi@localhost:3306/gluc"